version: "3"
services:
  broker.dmz:
    hostname: broker-dmz.choria.local
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    command: broker run --config /etc/choria/broker/broker.conf
    volumes:
      - ./config/broker/dmz:/etc/choria/broker
      - ./pki:/pki
    networks:
      - choria

  broker.east:
    hostname: broker-east.choria.local
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    command: broker run --config /etc/choria/broker/broker.conf
    volumes:
      - ./config/broker/east:/etc/choria/broker
      - ./pki:/pki
    networks:
      - choria

  broker.west:
    hostname: broker-west.choria.local
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    command: broker run --config /etc/choria/broker/broker.conf
    volumes:
      - ./config/broker/west:/etc/choria/broker
      - ./pki:/pki
    networks:
      - choria

  server.dmz:
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    domainname: choria.local
    command: server run --config /etc/choria/server.conf --debug
    volumes:
      - ./pki:/pki
      - ./config/server/dmz:/etc/choria
    networks:
      - choria

  server.east:
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    domainname: choria.local
    command: server run --config /etc/choria/server.conf --debug
    volumes:
      - ./pki:/pki
      - ./config/server/east:/etc/choria
    networks:
      - choria

  server.west:
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    domainname: choria.local
    command: server run --config /etc/choria/server.conf
    volumes:
      - ./pki:/pki
      - ./config/server/west:/etc/choria
    networks:
      - choria

  client.choria:
    hostname: client.choria.local
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    entrypoint: /bin/bash
    command: "-l"
    stdin_open: true
    tty: true
    volumes:
      - ./pki:/pki
      - ./config/client/client.conf:/home/choria/.choriarc
    environment: 
    - MCOLLECTIVE_CERTNAME=privileged.choria,
    - MCOLLECTIVE_ROLE=privileged.choria,
    - USER=choria
    networks:
      - choria

  client.east:
    hostname: client.choria.local
    image: docker.io/choria/choria:${CHORIA_TAG}
    dns_search: choria.local
    entrypoint: /bin/bash
    command: "-l"
    stdin_open: true
    tty: true
    volumes:
      - ./pki:/pki
      - ./config/client/east/client.conf:/home/choria/.choriarc
    environment: 
    - MCOLLECTIVE_CERTNAME=privileged.choria,
    - MCOLLECTIVE_ROLE=privileged.choria,
    - USER=choria
    networks:
      - choria
networks:
  choria: {}
